### ISSUE TITLE
Static.Serve should allow custom headers

### ISSUE THREAD

**Issue by insasho** [revel/revel#352]
Serving static files with `Cache-Control: max-age` headers is useful in a variety of situations. Example:
- favicons rarely change and usually want a cache-control max-age in weeks. Modern favicons can be large (300k+) due to the variety of presentations and contexts they are used in.
- fingerprinted javascript assets usually want to be cached for a long period of time because they don't change.
- jquery and CSS packages usually have version numbers in their names, and thus can have a high max-age as well.

Feature request: add the ability to set custom headers via parameters to Static.Serve or via a config file read by Static.Serve.

**Comment by brendensoares** [comment]
### TODO
- [ ] move this issue to the `revel/modules/static` module
- [ ] add config option for static file caching
- [ ] add cache header code to `static` module

**Comment by notzippy** [comment]
Closing now moved
