### ISSUE TITLE
Feature: revel command terminal color support

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#407]
http://wynnnetherland.com/journal/a-stylesheet-author-s-guide-to-terminal-colors

It would be great if we could colorify our terminal output, especially errors and especially especially test results!

I might just contribute this myself :)

**Comment by ptman** [comment]
Disabling this via config would be nice. I run a revel app in docker and forward logs to syslog. The ANSI color codes really only add clutter

**Comment by ptman** [comment]
Ah, a later commit made it configurable: https://github.com/revel/revel/commit/0ea6736c6434ac9a914840d8f4df6b5e874ff664

**Comment by brendensoares** [comment]
### TODO
- [ ] find places where color can enhance the dev user experience
- [ ] make it configurable
- [ ] make it so!

**Comment by notzippy** [comment]
Logger is now configurable ser pr #1213
