### ISSUE TITLE
Complete/Updated README

### ISSUE THREAD

**Issue by brendensoares** [revel/revel#432]
We should add a thorough overview and quick start guide to the README from the manual. It doesn't need to be as complete as the manual is, but it should highlight all the main features of Revel.

Also, we need to clearly point potential contributors to the contribution guide and begin requesting/enforcing that new pull requests are targeting the develop branch. We should mention our version milestone process so that others are aware of how we schedule issues for release.
### TODO
- [ ] Add section for built-in validators to manual
- [x] add CHANGELOG.md per release
- [ ] We should also add guidelines for submitting issues, especially steps to reproduce issues so we can avoid repetitive questioning. Should help reduce the effort needed to stay on top future issues.

**Comment by notzippy** [comment]
We will direct people to the wiki for guidelines and current status
